### DISCUSSION TITLE
iframe and startup.html

### DISCUSSION THREAD

**Discussion by jwijffels** [inception-project/inception#4249] [General]
Hello,

I'm testing out if inception can be put behind [ShinyProxy](https://www.shinyproxy.io/). 
Shinyproxy uses docker containers to manage applications. So I use the inception docker container. 
When the container starts up, Shinyproxy wraps the UI of inception in an iframe. In a normal shiny app this looks as follows:

![image](https://github.com/inception-project/inception/assets/1710810/556be584-5783-4667-bdf6-a498f49471ff)

when I put Inception behind Shinyproxy with the config shown below the iframe shows the startup.html from inception but because this is put into an iframe, the page is never refreshed. What's more is that the inception page seems to have been wrapped in a pre tag.

![image](https://github.com/inception-project/inception/assets/1710810/dc9e42fe-3992-4db3-83a9-69e781f34fe4)

I'm wondering if it would make sense to have an option in inception to remove the startup.html page. ShinyProxy checks every 'heartbeat' number of seconds if the app has come alive and shows a loading screen while it hasn't. 
If the inception app would directly go to login screen, I think I can put the app behind ShinyProxy. I've been trying to change the code myself but I'm not a java expert and the maven builds seem to fail after I followed the installation procedure here: https://inception-project.github.io/releases/29.5/docs/developer-guide.html#_setting_up_for_the_development_in_eclipse 

```
proxy:
  title: Inception TEST
  port: 80
  ## Availability: 3 minutes untill the docker container should be up (container-wait-time), timeout after 5 minutes of inactivity (heartbeat-timeout)
  heartbeat-rate: 4000
  heartbeat-timeout: 300000  
  container-wait-time: 180000
  authentication: none
  users:
    - name: jwijffels
      password: abc123
      groups: [ developers, administrators ]
  docker:
    url: http://localhost:2375
    port-range-start: 20000
  container-log-path: ./container-logs
  specs:
    - id: inception
      container-image: ghcr.io/inception-project/inception:29.5            
      port: 18080
      container-volumes: [ "/d/Jan/Dropbox/Work/2023/test/src/inception:/export"]
      hide-navbar-on-main-page-link: false
```

where the /export folder contains 

```
backup.keep.time=2592000
backup.interval=300
backup.keep.number=10
useSSL=false
allowPublicKeyRetrieval=true
serverTimezone=UTC
server.port=18080
wicket.core.csrf.enabled=false
wicket.core.csrf.no-origin-action=allow
remote-api.enabled=true
annotation.default-preferences.page-size=2000
```
