### ISSUE TITLE
Move definition of knowledge-base profiles into a file

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#296]
Instead of having the pre-defined remote knowledge-base profiles in code (`de.tudarmstadt.ukp.inception.kb.KnowledgeBases`), they should be provided in a file, e.g. in a YAML file, e.g.

```
kb-profiles:
  - name: British Museum
    type: sparql
    access:
      sparql-url: http://collection.britishmuseum.org/sparql
    mapping:
      subclass-of: http://www.w3.org/2000/01/rdf-schema#subClassOf
      instance-of: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
      ... <and so on for the other IRIs that we support>
  - name: Other ontology ...
```

When selecting such a pre-defined KB in the wizard, it should fill in the SPARQL URL as well as the IRI values on the next page.
