### ISSUE TITLE
Pre-defined importable knowledge bases

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#298]
After implementing #296, also allow adding pre-defined importable KBs. Instead of a SPARQL URL, these have a download URL from where they are downloaded and then imported as local KBs, e.g. 

```
kb-profiles:
  - name: Wine Ontology Example
    type: importable
    access:
      download-url: https://www.w3.org/TR/owl-guide/wine.rdf
    mapping:
      subclass-of: http://www.w3.org/2000/01/rdf-schema#subClassOf
      instance-of: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
      ... <and so on for the other IRIs that we support>
  - name: Other ontology ...
```
