### ISSUE TITLE
Fail to build using Github action

### ISSUE THREAD

**Issue by ihtsham** [inception-project/inception#3399]
I try to build the project using GitHub action using the following YML file.  
```
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

```

I am getting the following error while building 
![image](https://user-images.githubusercontent.com/4981604/192165469-a4919cca-66cb-49d3-8280-94591a969fed.png)
