### ISSUE TITLE
Error importing project: NullPointerException: Source document must be specified

### ISSUE THREAD

**Issue by dominiwe** [inception-project/inception#4366]
**Describe the bug**

Importing an export fails with the following error:
> `Error importing project: NullPointerException: Source document must be specified`

I am trying to export from one Inception instance and import into a _clean_ freshly deployed second instance but it unfortunately fails.

Both instances have the same version deployed but the old one used HSQLDB while the new one uses MariaDB.

**To Reproduce**

Use the webinterface to export a project in one instance, use the webinterface to import it in the other instance.

**Expected behavior**
Expected the export/import over the webinterface to work.

**Screenshots**
No screenshots, but a stacktrace:

[error_trace_app.txt](https://github.com/inception-project/inception/files/13613871/error_trace_app.txt)

And this is the docker compose file I used to set up inception:

```yaml
networks:
  web:
    external: true
  inception-net:

services:
  db:
    image: "mariadb:10.7"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=inception
      - MYSQL_USER=${DBUSER:-inception}
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=${DBPASSWORD:-ADIFFERENTPASSWORDOFCOURSE}
    volumes:
      - /inception/data/inception/db-data:/var/lib/mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_bin"]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${DBPASSWORD:-ADIFFERENTPASSWORDOFCOURSE}", "-u${DBUSER:-inception}"]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      inception-net:
  app:
    image: "${INCEPTION_IMAGE:-ghcr.io/inception-project/inception}:${INCEPTION_VERSION:-29.9}"
    environment:
      - INCEPTION_DB_DIALECT=org.hibernate.dialect.MariaDB103Dialect
      - INCEPTION_DB_DRIVER=org.mariadb.jdbc.Driver
      - INCEPTION_DB_URL=jdbc:mariadb://db:3306/inception?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      - INCEPTION_DB_USERNAME=${DBUSER:-inception}
      - INCEPTION_DB_PASSWORD=${DBPASSWORD:-ADIFFERENTPASSWORDOFCOURSE}
      - JAVA_OPTS=-Dspring.jpa.properties.hibernate.dialect.storage_engine=innodb
    volumes:
      - /inception/data/inception/app-data:/export
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.inception.entryPoints=websecure # entrypoint
      - traefik.http.routers.inception.rule=Host(`myurl`) # host
      - traefik.http.routers.inception.service=inception # service to target
      - traefik.http.routers.inception.tls=true # use tls
      - traefik.http.routers.inception.tls.certResolver=lets-encrypt
      - traefik.http.services.inception.loadbalancer.server.port=8080
      - traefik.http.services.inception.loadbalancer.passhostheader=true
    networks:
      web:
      inception-net:
```

**Please complete the following information:**
 - Version and build ID:  INCEpTION -- 29.0 (2023-08-08 14:34:53, build 86d5bbd2) 
 - OS: Linux
 - Browser: Firefox
